---
- name: Install Apache
  ansible.builtin.apt:
    name: apache2
    state: present

- name: Install PHP
  ansible.builtin.apt:
    name: php
    state: present

- name: Install PHP-MySQL
  ansible.builtin.apt:
    name: php-mysql
    state: present
